site_name: NadekoBot
repo_url: https://github.com/Kwoth/NadekoBot
pages:
- Home: index.md
- About: about.md
- Guides:
    - Windows Guide: guides/Windows Guide.md
    - Linux Guide: guides/Linux Guide.md
    - OSX Guide: guides/OSX Guide.md
    - Building from Source: guides/Building from Source.md
    - Docker Guide: guides/Docker Guide.md
- Commands:
    - Readme: Readme.md
    - Commands List: Commands List.md
- Permissions System: Permissions System.md
- JSON Explanations: JSON Explanations.md
- Custom Reactions: Custom Reactions.md
- Frequently Asked Questions: Frequently Asked Questions.md
- Contribution Guide: Contribution Guide.md
- ❤ Donate ❤: Donate.md

theme: readthedocs
